version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  publisher_api:
    image: publisher_api:latest
    restart: on-failure
    depends_on:
      - "rabbitmq"
    build:
      context: ./publisher_api
      dockerfile: Dockerfile
    ports:
      - "8080:80"     
    networks:
      - dockerapi-dev  
  
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
      - dockerapi-dev

  worker:
    image: worker:latest
    restart: on-failure
    depends_on:
      - "rabbitmq"
    build:
      context: ./worker
      dockerfile: Dockerfile
    networks:
      - dockerapi-dev 
