version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  publisher_api:
    image: publisher_api:latest
    restart: on-failure
    depends_on:
      - "rabbitmq"
    build:
      context: ./publisher_api
      dockerfile: Dockerfile
    ports:
      - "8080:80"     
    networks:
      - dockerapi-dev  
  
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    networks:
      - dockerapi-dev

  worker:
    image: worker:latest
    restart: on-failure
    depends_on:
      - "rabbitmq"
    build:
      context: ./worker
      dockerfile: Dockerfile
    networks:
      - dockerapi-dev 
